### ISSUE TITLE
出现这个情况

### ISSUE THREAD

**Issue by wenroubinglen** [yuanfangqiao/euanka#1]
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddocker-compose%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied

**Comment by yuanfangqiao** [comment]
@wenroubinglen  已经提示，是你的docker没有权限
复制 dial unix /var/run/docker.sock: connect: permission denied 到百度或者google解决
大致有，
给当前用户分配docekr权限，使用sudo su 切换到root权限
