### ISSUE TITLE
tts4个g语音包一直是卡在280兆下不下来

### ISSUE THREAD

**Issue by wenroubinglen** [yuanfangqiao/euanka#2]

**Comment by wenroubinglen** [comment]
![image](https://github.com/yuanfangqiao/euanka/assets/47852662/80a8ee14-c47a-46de-8b18-7eb2ccf18b22)

**Comment by wenroubinglen** [comment]
卡在这不动了

**Comment by yuanfangqiao** [comment]
@wenroubinglen 尝试使用docker pull registry.cn-shenzhen.aliyuncs.com/yuanfangqiao/vits:0.2下载

**Comment by yuanfangqiao** [comment]
![image](https://github.com/yuanfangqiao/euanka/assets/113848355/8cd11090-339b-4be4-b879-56830db587f0)
![image](https://github.com/yuanfangqiao/euanka/assets/113848355/e0ee1c92-54cd-4981-b644-a8f22370b884)

**Comment by yuanfangqiao** [comment]
我使用外网的docker提供的体验容器能下载，应该不是镜像的问题
https://labs.play-with-docker.com/

**Comment by yuanfangqiao** [comment]
可以根据 
https://github.com/yuanfangqiao/VITS-Umamusume-voice-synthesizer/tree/main/euanka/ubuntu-python38 

https://github.com/yuanfangqiao/VITS-Umamusume-voice-synthesizer/blob/main/Dockerfile

本地构建tts 镜像
